apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-minikube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-minikube
  template:
    metadata:
      labels:
        app: sample-minikube
    spec:
      containers:
      - name: sample-minikube
        image: sample-minikube:latest
        ports:
        - containerPort: 5000
        
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "250m"
