apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-minikube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-minikube
  template:
    metadata:
      labels:
        app: sample-minikube
    spec:
      containers:
      - name: sample-minikube
        image: gakalmar/sample-minikube:latest
        ports:
        - containerPort: 5000
