apiVersion: v1
kind: Service
metadata:
  name: sample-minikube-service
spec:
  type: NodePort
  selector:
    app: sample-minikube
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30001


